# 加解密根密码  全局配置文件
jasypt:
  encryptor:
    password: pigx #根密码
# redis 相关
spring:
  redis:
    password:
    host: ${REDIS-HOST:pigx-redis}
  # json全局序列化配置 驼峰命名 忽略 null
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s
# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
#      # 逻辑已删除值(默认为 0)
      logic-delete-value: 0
#      # 逻辑未删除值(默认为 1)
      logic-not-delete-value: 1

# 统一鉴权相关配置
  authorization:
    # 鉴权策略名称，默认空
    name: pigX OAuth
    # 需要开启鉴权URL的正则，默认匹配所有
    auth-regex: ^.*$
    # 鉴权作用域列表配置,默认空
    authorization-scope-list:
    # 鉴权作用域名称,默认空
      - scope: server
        # 鉴权作用域描述,默认空
        description: server all
        # 校验token的地址列表,默认空
    token-url-list:
      - http://${GATEWAY-HOST:pigx-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token

## spring security 配置
security:
  oauth2:
    client:
      # 默认放行url,如果子模块重写这里的配置就会被覆盖
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH-HOST:pigx-auth}/oauth/check_token