## spring security 配置
security:
  oauth2:
    client:
#    Jasypt ENC 标签
      client-id: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      client-secret: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      scope: server
      # 默认放行url 不用登录判断权限,如果子模块重写这里的配置就会被覆盖
      ignore-urls:
      - /actuator/**
      - /v2/api-docs
      # 放行 /greet  不用登录可以访问
#      - /greet

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:orgtec}
    url: jdbc:mysql://${MYSQL-HOST:pigx-mysql}:${MYSQL-PORT:3366}/${MYSQL-DB:pigxx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8

# 日志
# Logger Config
logging:
  level:
    com.pig4cloud.pigx.farm.mapper: debug