## spring security 配置
security:
  oauth2:
    client:
#      ENC 标签 pig
      client-id: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      client-secret: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/*
        - /social/info/*
        - /mobile/*
        - /log/save

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:orgtec}
    url: jdbc:mysql://${MYSQL-HOST:pigx-mysql}:${MYSQL-PORT:3366}/${MYSQL-DB:pigxx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

# 文件系统 (提供测试环境，不要乱传)
minio:
  url: https://minio.pig4cloud.com
  access-key: ENC(O4GgJmcJLQAnvfz+RRq65aps5HgbWQXZ)
  secret-key: ENC(O4GgJmcJLQAnvfz+RRq65aps5HgbWQXZ)

# Logger Config
logging:
  level:
    com.pig4cloud.pigx.admin.mapper: debug

# 租户表维护
pigx:
  tenant:
    column: tenant_id
    tables:
      - sys_user
      - sys_role
      - sys_dept
      - sys_log
      - sys_social_details
      - sys_dict
      - sys_dict_item
      - sys_log
